### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by nordic81** [RokitSalad/Helpful.CircuitBreaker#4]
Hello,
we would like to use your library, but the license file is missing (the nuget link points to a non-existing file).
Could you please provide a license file? (If you don't care, you could use e.g. the MIT license...)

kind regards
Norbert

**Comment by RokitSalad** [comment]
Hadn't noticed :) thanks.

This is free to use - no strings.

**Comment by nordic81** [comment]
Hi,
thank you for providing a license file.
But since we intend to use the package in a commercial application, the GPL
isn't an option for us; there's no way our company will publish the source
code.
Is there any chance you will "downgrade" the license to LGPL or another
license that will allow us to use your package without having us to provide
the source code of our application?

Kind regards
Norbert

2015-11-15 0:25 GMT+01:00 RokitSalad <notifications@github.com>:

**Comment by RokitSalad** [comment]
Yes - I hadn't noticed the distinction to be honest. I'll do that for you tonight.


Pete.


Sent from Outlook Mobile






On Tue, Dec 1, 2015 at 9:45 AM -0800, "nordic81" <notifications@github.com> wrote:





Hi,
thank you for providing a license file.
But since we intend to use the package in a commercial application, the GPL
isn't an option for us; there's no way our company will publish the source
code.
Is there any chance you will "downgrade" the license to LGPL or another
license that will allow us to use your package without having us to provide
the source code of our application?

Kind regards
Norbert

2015-11-15 0:25 GMT+01:00 RokitSalad <notifications@github.com>:

> Hadn't noticed :) thanks.
>
> This is free to use - no strings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RokitSalad/Helpful.CircuitBreaker/issues/4#issuecomment-156757637>
> .
>


---
